server:
  port: 8080

spring:
  datasource:
    url: dbc:mysql://wktime.c7qc2o24klkn.eu-north-1.rds.amazonaws.com:3306/wktime
    username: root
    password: welee
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "wktime-jwt-secret-please-change-this-in-production-1234567890"
    expiry-minutes: 720
  mail:
    enabled: false
    from: "noreply@wktime.local"

  # Example SMTP setup:
  # mail:
  #   enabled: true
  #   from: "your-email@gmail.com"
